import { AssistantPublicProfile, BookingOrder, ServicePackage, ServiceScene, StaffMealBrief } from './types';

export const scenes: ServiceScene[] = [
  {
    id: 'scene_001',
    code: 'business_dinner',
    name: '商务宴请',
    summary: '让正式饭局更自然，让接待更有分寸。',
    description: '适合客户宴请、合作方接待、重要项目沟通等场景，提供餐前准备、现场礼宾与氛围协同。',
    cover: '/assets/images/scene-business-dinner.jpg',
    tags: ['客户宴请', '项目沟通', '礼宾接待'],
    serviceScope: ['餐前简报', '现场礼仪协同', '话题氛围辅助', '平台客服跟进']
  },
  {
    id: 'scene_002',
    code: 'private_tea',
    name: '私人茶会',
    summary: '茶艺师、空间氛围与轻社交节奏的得体协同。',
    description: '适合私享茶叙、客户小范围会面、长辈或重要关系维护，以茶艺师和礼宾流程降低生硬感。',
    cover: '/assets/images/scene-private-tea.jpg',
    tags: ['茶艺师', '私享茶叙', '关系维护'],
    serviceScope: ['茶席流程建议', '茶艺师服务', '轻话题准备', '会后复盘']
  },
  {
    id: 'scene_003',
    code: 'wine_reception',
    name: '高端酒会',
    summary: '侍酒师、酒会礼仪与圈层交流的克制协同。',
    description: '适合高端酒会、品牌私享会和商务沙龙，由侍酒师与礼宾人员协同现场节奏与宾客照应。',
    cover: '/assets/images/scene-wine-reception.jpg',
    tags: ['侍酒师', '商务酒会', '圈层沙龙'],
    serviceScope: ['侍酒建议', '宾客照应', '话题分寸提醒', '现场反馈']
  },
  {
    id: 'scene_004',
    code: 'golf_social',
    name: '高尔夫商务同场',
    summary: '球局礼仪、节奏提醒与商务关系维护协同。',
    description: '适合高尔夫商务球局、客户休闲接待与圈层活动，强调礼仪、边界、节奏和自然互动。',
    cover: '/assets/images/scene-golf-social.jpg',
    tags: ['高尔夫', '商务同场', '礼仪协同'],
    serviceScope: ['球局礼仪提醒', '动线与节奏协同', '客户照应', '服务复盘']
  },
  {
    id: 'scene_005',
    code: 'city_concierge',
    name: '城市临时管家',
    summary: '当地城市礼宾、到访动线与临时事项统筹。',
    description: '适合重要客户临时到访、城市接待和多点行程协同，提供当地礼宾管家式服务支持。',
    cover: '/assets/images/scene-city-concierge.jpg',
    tags: ['城市礼宾', '临时管家', '到访接待'],
    serviceScope: ['到访动线', '本地礼宾建议', '临时事项协调', '客服跟进']
  },
  {
    id: 'scene_006',
    code: 'closed_salon',
    name: '闭门沙龙',
    summary: '小范围圈层交流、议题节奏与现场分寸协同。',
    description: '适合私董会、会员制空间小型交流和重点圈层私享局，提供议题准备、宾客照应和现场节奏协同。',
    cover: '/assets/images/scene-closed-salon.jpg',
    tags: ['闭门交流', '议题控场', '圈层沙龙'],
    serviceScope: ['议题节奏准备', '宾客照应', '轻话题协同', '内部复盘']
  },
  {
    id: 'scene_007',
    code: 'art_preview',
    name: '艺术展览',
    summary: '观展礼宾、审美话题与私享预览协同。',
    description: '适合画廊预览、艺术展览、收藏交流和文化场景会面，强调审美话题、动线安排和得体照应。',
    cover: '/assets/images/scene-art-preview.jpg',
    tags: ['艺术展览', '观展动线', '审美话题'],
    serviceScope: ['观展动线建议', '审美话题准备', '嘉宾照应', '服务后反馈']
  },
  {
    id: 'scene_008',
    code: 'tennis_social',
    name: '运动社交',
    summary: '网球、轻运动与会后轻餐的自然衔接。',
    description: '适合网球、轻运动、俱乐部休闲会面和会后轻餐衔接，保持健康、自然和得体边界。',
    cover: '/assets/images/scene-tennis-social.jpg',
    tags: ['网球社交', '轻运动', '会后轻餐'],
    serviceScope: ['运动礼仪提醒', '场地动线协同', '会后轻餐衔接', '服务复盘']
  },
  {
    id: 'scene_009',
    code: 'brand_private_event',
    name: '品牌私享会',
    summary: '贵宾接待、现场礼宾与体验节奏维护。',
    description: '适合高端品牌私享会、贵宾预览和会员体验活动，提供接待秩序、礼宾动线和异常提醒。',
    cover: '/assets/images/scene-brand-private-event.jpg',
    tags: ['品牌私享会', '贵宾接待', '体验节奏'],
    serviceScope: ['贵宾接待', '现场礼宾', '体验节奏维护', '异常提醒']
  }
];

export const packages: ServicePackage[] = [
  {
    id: 'pkg_001',
    sceneId: 'scene_001',
    name: '标准商务协同',
    subtitle: '适合 4-8 人正式宴请',
    durationHours: 3,
    assistantCount: 1,
    depositAmount: 600,
    serviceFee: 1800,
    includes: ['1 位服务人员', '餐前简报', '服务边界确认', '现场协同反馈']
  },
  {
    id: 'pkg_002',
    sceneId: 'scene_001',
    name: '重要客户接待',
    subtitle: '适合高规格客户晚宴',
    durationHours: 4,
    assistantCount: 2,
    depositAmount: 1200,
    serviceFee: 3600,
    includes: ['2 位服务人员', '专属餐前准备', '客户背景梳理', '主管复核简报']
  },
  {
    id: 'pkg_003',
    sceneId: 'scene_002',
    name: '私享茶叙协同',
    subtitle: '适合 3-8 人茶会与关系维护',
    durationHours: 3,
    assistantCount: 1,
    depositAmount: 800,
    serviceFee: 2600,
    includes: ['茶艺师服务', '茶席流程建议', '轻话题简报', '会后反馈']
  },
  {
    id: 'pkg_004',
    sceneId: 'scene_003',
    name: '酒会侍酒礼宾',
    subtitle: '适合品牌酒会、商务沙龙和私享会',
    durationHours: 4,
    assistantCount: 2,
    depositAmount: 1500,
    serviceFee: 5200,
    includes: ['侍酒师协同', '宾客照应', '现场节奏维护', '风险边界提醒']
  },
  {
    id: 'pkg_005',
    sceneId: 'scene_004',
    name: '高尔夫商务同场',
    subtitle: '适合客户球局和圈层活动',
    durationHours: 5,
    assistantCount: 1,
    depositAmount: 1200,
    serviceFee: 4800,
    includes: ['球局礼仪提醒', '动线与节奏协同', '客户照应', '服务复盘']
  },
  {
    id: 'pkg_006',
    sceneId: 'scene_005',
    name: '城市临时管家',
    subtitle: '适合重要客户临时到访与多点行程',
    durationHours: 6,
    assistantCount: 1,
    depositAmount: 1600,
    serviceFee: 5800,
    includes: ['本地礼宾建议', '到访动线协同', '临时事项统筹', '客服全程跟进']
  },
  {
    id: 'pkg_007',
    sceneId: 'scene_006',
    name: '闭门沙龙协同',
    subtitle: '适合私董会、会员制空间小范围交流',
    durationHours: 4,
    assistantCount: 2,
    depositAmount: 1800,
    serviceFee: 6200,
    includes: ['议题节奏准备', '宾客照应', '轻话题协同', '内部复盘']
  },
  {
    id: 'pkg_008',
    sceneId: 'scene_007',
    name: '艺术展览礼宾',
    subtitle: '适合观展、画廊预览和文化场景会面',
    durationHours: 3,
    assistantCount: 1,
    depositAmount: 1200,
    serviceFee: 4200,
    includes: ['观展动线建议', '审美话题准备', '嘉宾照应', '服务后反馈']
  },
  {
    id: 'pkg_009',
    sceneId: 'scene_008',
    name: '运动社交协同',
    subtitle: '适合网球、轻运动和会后轻餐衔接',
    durationHours: 4,
    assistantCount: 1,
    depositAmount: 1200,
    serviceFee: 4200,
    includes: ['运动礼仪提醒', '场地动线协同', '会后轻餐衔接', '服务复盘']
  },
  {
    id: 'pkg_010',
    sceneId: 'scene_009',
    name: '品牌私享会礼宾',
    subtitle: '适合贵宾预览、会员体验和高端活动',
    durationHours: 4,
    assistantCount: 2,
    depositAmount: 2000,
    serviceFee: 6800,
    includes: ['贵宾接待', '现场礼宾', '体验节奏维护', '异常提醒']
  }
];

const complianceNote = '仅展示工作名、城市、公开能力和合规形象照；不展示真实联系方式，沟通统一由平台客服或受控消息系统承接。';

export const assistants: AssistantPublicProfile[] = [
  {
    id: 'ast_business_01',
    assistantNo: 'BA-0218',
    workName: '林澈',
    city: '上海',
    avatarUrl: '/assets/assistants/business-01.jpg',
    styleTags: ['沉稳', '知性', '正式感'],
    sceneSkills: ['商务宴请', '客户接待', '项目沟通'],
    businessSkills: ['主陪话题承接', '座次礼仪提醒', '正式开场协同'],
    talents: ['钢琴十级', '商务英语接待 50+ 场', '美术馆观展 80+ 次'],
    intro: '适合重要客户晚宴。稳住开场，接住冷场，不抢主位。',
    complianceNote,
    recommendReason: '正式局优先推荐，表达克制，边界稳定，能把生硬场面拉回自然节奏。'
  },
  {
    id: 'ast_business_02',
    assistantNo: 'BA-0266',
    workName: '许知意',
    city: '北京',
    avatarUrl: '/assets/assistants/business-02.jpg',
    styleTags: ['大方', '亲和', '控场'],
    sceneSkills: ['商务宴请', '客户接待', '轻商务接待'],
    businessSkills: ['轻松破冰', '宾客照应', '话题延展'],
    talents: ['主持训练 120 小时', '网球 NTRP 3.0', '流行钢琴曲目 18 首'],
    intro: '适合第一次见面的局。开口自然，分寸清楚，场子不冷。',
    complianceNote,
    recommendReason: '适合陌生客户或跨圈层饭局，能降低尴尬感，让交流先顺起来。'
  },
  {
    id: 'ast_business_03',
    assistantNo: 'BA-0317',
    workName: '周予安',
    city: '深圳',
    avatarUrl: '/assets/assistants/business-03.jpg',
    styleTags: ['干练', '清爽', '礼宾'],
    sceneSkills: ['商务宴请', '客户接待', '城市临时管家'],
    businessSkills: ['接待动线', '行程衔接', '现场节奏提醒'],
    talents: ['半马 2小时05分', '英语寒暄 80+ 句', '摄影修图 300+ 张'],
    intro: '适合高规格接待。逻辑清楚，反应快，执行不拖泥带水。',
    complianceNote,
    recommendReason: '适合外地客户到访后的晚宴衔接，能把动线、称呼和节奏处理干净。'
  },
  {
    id: 'ast_business_04',
    assistantNo: 'BA-0412',
    workName: '沈清予',
    city: '杭州',
    avatarUrl: '/assets/assistants/business-04.jpg',
    styleTags: ['温和', '书卷气', '稳'],
    sceneSkills: ['商务宴请', '私人茶会', '项目沟通'],
    businessSkills: ['行业轻话题', '安静承接', '禁忌提醒'],
    talents: ['国画花鸟 60+ 幅', '古典音乐歌单 200 首', '瑜伽 200 小时训练'],
    intro: '适合不宜太热闹的局。存在感轻，但能稳住礼貌和气氛。',
    complianceNote,
    recommendReason: '适合长辈、重要关系维护和慢热型客户，气质安静，不制造压迫感。'
  },
  {
    id: 'ast_business_05',
    assistantNo: 'BA-0489',
    workName: '唐若宁',
    city: '成都',
    avatarUrl: '/assets/assistants/business-05.jpg',
    styleTags: ['松弛', '会接话', '轻商务'],
    sceneSkills: ['商务宴请', '轻商务接待', '高端酒会'],
    businessSkills: ['自然接梗', '场面照应', '饭后复盘'],
    talents: ['声乐训练 4 年', '羽毛球校队 2 年', '展览导览 30+ 场'],
    intro: '适合气氛要轻松的局。会接话，会留白，不把场面推过头。',
    complianceNote,
    recommendReason: '适合轻商务接待或小范围会面，优势是松弛但不散，活跃但不越界。'
  },
  {
    id: 'ast_business_06',
    assistantNo: 'BA-0560',
    workName: '程以安',
    city: '广州',
    avatarUrl: '/assets/assistants/business-06.jpg',
    styleTags: ['利落', '商务感', '细节控'],
    sceneSkills: ['商务宴请', '项目沟通', '客户接待'],
    businessSkills: ['餐前信息整理', '称呼核对', '风险话题避让'],
    talents: ['商务接待复盘 70+ 场', '普拉提训练 180 小时', '粤语普通话双语切换'],
    intro: '适合目标明确的饭局。提前做功课，现场少出错。',
    complianceNote,
    recommendReason: '适合项目推进和正式宴请，强项是准备细、执行稳、反馈准。'
  },
  {
    id: 'ast_tea_01',
    assistantNo: 'BA-0616',
    workName: '苏言',
    city: '杭州',
    avatarUrl: '/assets/assistants/tea-01.jpg',
    styleTags: ['清雅', '安静', '茶席感'],
    sceneSkills: ['私人茶会', '商务宴请', '客户接待'],
    businessSkills: ['茶席流程', '慢节奏破冰', '长辈接待'],
    talents: ['茶艺培训 160 小时', '古琴曲目 8 首', '书法临帖 3 年'],
    intro: '适合安静茶局。节奏慢，话不多，但每句都有位置。',
    complianceNote,
    recommendReason: '适合长辈会面、关系维护和小范围私享茶叙，能把节奏压稳。'
  },
  {
    id: 'ast_tea_02',
    assistantNo: 'BA-0673',
    workName: '顾清岚',
    city: '苏州',
    avatarUrl: '/assets/assistants/tea-02.jpg',
    styleTags: ['温婉', '礼貌', '文化感'],
    sceneSkills: ['私人茶会', '客户接待', '城市临时管家'],
    businessSkills: ['茶点动线', '称呼礼仪', '轻话题准备'],
    talents: ['苏式评弹曲目 10 首', '茶席布置 50+ 次', '园林导览 40+ 次'],
    intro: '适合偏中式的关系局。懂礼貌，也懂什么时候不说话。',
    complianceNote,
    recommendReason: '适合江浙客户、长辈接待和文化型茶会，气质稳，细节感强。'
  },
  {
    id: 'ast_tea_03',
    assistantNo: 'BA-0729',
    workName: '叶听晚',
    city: '上海',
    avatarUrl: '/assets/assistants/tea-03.jpg',
    styleTags: ['知性', '克制', '审美好'],
    sceneSkills: ['私人茶会', '项目沟通', '高端酒会'],
    businessSkills: ['艺术话题', '轻商务承接', '边界提醒'],
    talents: ['美术馆导览 60+ 场', '油画临摹 40+ 幅', '英语阅读书单 120 本'],
    intro: '适合有审美门槛的局。话题干净，不油，不浮。',
    complianceNote,
    recommendReason: '适合艺术、品牌、文化类客户茶叙，能把话题做得高级但不炫技。'
  },
  {
    id: 'ast_tea_04',
    assistantNo: 'BA-0788',
    workName: '陆青禾',
    city: '南京',
    avatarUrl: '/assets/assistants/tea-04.jpg',
    styleTags: ['柔和', '耐心', '会照应'],
    sceneSkills: ['私人茶会', '轻商务接待', '客户接待'],
    businessSkills: ['照顾慢热客人', '茶水节奏', '局面降噪'],
    talents: ['瑜伽 300 小时训练', '插花作品 80+ 件', '普通话一级乙等'],
    intro: '适合慢热客户。能让人放松，但不会让场面失焦。',
    complianceNote,
    recommendReason: '适合人数少、关系敏感的茶局，强项是安抚节奏和照应边角客人。'
  },
  {
    id: 'ast_tea_05',
    assistantNo: 'BA-0835',
    workName: '宋知微',
    city: '北京',
    avatarUrl: '/assets/assistants/tea-05.jpg',
    styleTags: ['清醒', '稳准', '书卷气'],
    sceneSkills: ['私人茶会', '项目沟通', '商务宴请'],
    businessSkills: ['观点提炼', '话题收束', '禁忌避让'],
    talents: ['辩论赛校队 2 年', '古典文学阅读 100+ 本', '普拉提训练 160 小时'],
    intro: '适合要谈事的茶局。能把散话收住，也能把话题递出去。',
    complianceNote,
    recommendReason: '适合项目沟通前置茶叙，优势是逻辑感强，能帮局面回到重点。'
  },
  {
    id: 'ast_tea_06',
    assistantNo: 'BA-0891',
    workName: '温栀',
    city: '成都',
    avatarUrl: '/assets/assistants/tea-06.jpg',
    styleTags: ['亲和', '自然', '茶艺师'],
    sceneSkills: ['私人茶会', '轻商务接待', '城市临时管家'],
    businessSkills: ['茶艺展示', '轻松寒暄', '会后反馈'],
    talents: ['茶艺师课程 180 小时', '民谣吉他曲目 20 首', '徒步 100+ 公里'],
    intro: '适合轻松茶叙。亲和但不黏，热络但不闹。',
    complianceNote,
    recommendReason: '适合朋友茶会和轻关系维护，能把舒服感做出来，又不显得刻意。'
  },
  {
    id: 'ast_wine_01',
    assistantNo: 'BA-0918',
    workName: '陈若白',
    city: '上海',
    avatarUrl: '/assets/assistants/wine-01.jpg',
    styleTags: ['成熟', '利落', '酒会感'],
    sceneSkills: ['高端酒会', '商务宴请', '项目沟通'],
    businessSkills: ['侍酒话题', '宾客照应', '社交距离控制'],
    talents: ['WSET 二级', '爵士乐歌单 300 首', '商务沙龙协同 40+ 场'],
    intro: '适合品牌酒会。能照应，能退场，不制造多余热闹。',
    complianceNote,
    recommendReason: '适合高端酒会和品牌私享会，懂酒但不劝酒，控距离很稳。'
  },
  {
    id: 'ast_wine_02',
    assistantNo: 'BA-0972',
    workName: '梁景初',
    city: '广州',
    avatarUrl: '/assets/assistants/wine-02.jpg',
    styleTags: ['大气', '从容', '国际化'],
    sceneSkills: ['高端酒会', '客户接待', '城市临时管家'],
    businessSkills: ['英文寒暄', '酒会礼仪', '多方照应'],
    talents: ['英语商务接待 80+ 场', '拉丁舞训练 3 年', '红酒品鉴笔记 120 篇'],
    intro: '适合人多的酒会。看得见全场，也守得住边界。',
    complianceNote,
    recommendReason: '适合多方宾客同时在场的活动，强项是照应、寒暄和动线感。'
  },
  {
    id: 'ast_wine_03',
    assistantNo: 'BA-1030',
    workName: '夏知夏',
    city: '深圳',
    avatarUrl: '/assets/assistants/wine-03.jpg',
    styleTags: ['明亮', '会破冰', '不浮夸'],
    sceneSkills: ['高端酒会', '轻商务接待', '商务宴请'],
    businessSkills: ['快速破冰', '话题串联', '结束收口'],
    talents: ['声乐舞台 20+ 次', '网球训练 260 小时', '活动主持 30+ 场'],
    intro: '适合需要打开气氛的酒会。热度够，但不会过火。',
    complianceNote,
    recommendReason: '适合偏轻松的酒会和圈层沙龙，能打开第一轮交流。'
  },
  {
    id: 'ast_wine_04',
    assistantNo: 'BA-1086',
    workName: '何映宁',
    city: '北京',
    avatarUrl: '/assets/assistants/wine-04.jpg',
    styleTags: ['冷静', '高级', '审美型'],
    sceneSkills: ['高端酒会', '私人茶会', '项目沟通'],
    businessSkills: ['艺术品牌话题', '重要客户距离感', '分寸提醒'],
    talents: ['美术馆导览 90+ 场', '法语寒暄 60 句', '普拉提训练 200 小时'],
    intro: '适合品牌局。气质冷静，话题有质感，不急着靠近。',
    complianceNote,
    recommendReason: '适合艺术、奢品、品牌类私享会，审美和距离感都在线。'
  },
  {
    id: 'ast_wine_05',
    assistantNo: 'BA-1151',
    workName: '孟听澜',
    city: '杭州',
    avatarUrl: '/assets/assistants/wine-05.jpg',
    styleTags: ['温柔', '细致', '礼宾'],
    sceneSkills: ['高端酒会', '客户接待', '商务宴请'],
    businessSkills: ['宾客照应', '座位动线', '酒会复盘'],
    talents: ['小提琴曲目 15 首', '插花作品 100+ 件', '礼仪培训 120 小时'],
    intro: '适合规格高但不宜张扬的酒会。细节好，存在感刚好。',
    complianceNote,
    recommendReason: '适合重要客户和贵宾照应，强项是细节、礼貌和稳定反馈。'
  },
  {
    id: 'ast_wine_06',
    assistantNo: 'BA-1198',
    workName: '江晚晴',
    city: '成都',
    avatarUrl: '/assets/assistants/wine-06.jpg',
    styleTags: ['松弛', '自然', '社交感'],
    sceneSkills: ['高端酒会', '轻商务接待', '城市临时管家'],
    businessSkills: ['圈层介绍', '轻松接话', '情绪观察'],
    talents: ['爵士舞训练 4 年', '摄影作品 500+ 张', '威士忌品鉴笔记 80 篇'],
    intro: '适合不想冷场的局。自然接话，不硬推关系。',
    complianceNote,
    recommendReason: '适合私享酒会和朋友局，能让氛围轻一点，但边界清楚。'
  },
  {
    id: 'ast_golf_01',
    assistantNo: 'BA-1260',
    workName: '林予鹿',
    city: '深圳',
    avatarUrl: '/assets/assistants/golf-01.jpg',
    styleTags: ['运动感', '清爽', '高尔夫'],
    sceneSkills: ['高尔夫商务同场', '客户接待', '城市临时管家'],
    businessSkills: ['球局礼仪', '动线节奏', '客户照应'],
    talents: ['高尔夫练习 300 小时', '10 公里 55 分钟', '英语球局寒暄 50 句'],
    intro: '适合商务球局。懂节奏，懂礼仪，也懂什么时候安静。',
    complianceNote,
    recommendReason: '适合客户球局和休闲接待，强项是运动场景里的分寸和照应。'
  },
  {
    id: 'ast_golf_02',
    assistantNo: 'BA-1314',
    workName: '乔安然',
    city: '上海',
    avatarUrl: '/assets/assistants/golf-02.jpg',
    styleTags: ['活力', '亲和', '边界感'],
    sceneSkills: ['高尔夫商务同场', '轻商务接待', '商务宴请'],
    businessSkills: ['运动话题', '轻松破冰', '场面照应'],
    talents: ['网球 NTRP 3.5', '高尔夫下场 30+ 次', '爵士鼓基础曲目 12 首'],
    intro: '适合轻松球局。能打开话题，但不会把场子带偏。',
    complianceNote,
    recommendReason: '适合需要轻松气氛的球局，运动话题自然，分寸不冒进。'
  },
  {
    id: 'ast_golf_03',
    assistantNo: 'BA-1377',
    workName: '姜一禾',
    city: '北京',
    avatarUrl: '/assets/assistants/golf-03.jpg',
    styleTags: ['利落', '专注', '执行强'],
    sceneSkills: ['高尔夫商务同场', '项目沟通', '客户接待'],
    businessSkills: ['时间提醒', '规则礼仪', '复盘记录'],
    talents: ['高尔夫规则学习 100 小时', '普拉提 200 小时训练', '半马 2小时12分'],
    intro: '适合时间紧的球局。执行利落，不让流程散掉。',
    complianceNote,
    recommendReason: '适合上午球局接下午商务安排，能把时间和节奏盯住。'
  },
  {
    id: 'ast_golf_04',
    assistantNo: 'BA-1425',
    workName: '贺南星',
    city: '杭州',
    avatarUrl: '/assets/assistants/golf-04.jpg',
    styleTags: ['安静', '耐心', '观察力'],
    sceneSkills: ['高尔夫商务同场', '私人茶会', '城市临时管家'],
    businessSkills: ['情绪观察', '低干扰照应', '服务后复盘'],
    talents: ['瑜伽 300 小时训练', '徒步 200+ 公里', '摄影作品 400+ 张'],
    intro: '适合不喜欢被打扰的客户。照应到位，但不贴身。',
    complianceNote,
    recommendReason: '适合重要客户休闲接待，优势是低干扰、观察细、反馈准。'
  },
  {
    id: 'ast_golf_05',
    assistantNo: 'BA-1489',
    workName: '安予希',
    city: '成都',
    avatarUrl: '/assets/assistants/golf-05.jpg',
    styleTags: ['开朗', '运动', '松弛'],
    sceneSkills: ['高尔夫商务同场', '轻商务接待', '高端酒会'],
    businessSkills: ['自然破冰', '运动社交', '轻松收口'],
    talents: ['羽毛球市级业余赛 8 强', '高尔夫练习 180 小时', '民谣吉他曲目 25 首'],
    intro: '适合轻社交球局。把气氛打开，但不显得用力。',
    complianceNote,
    recommendReason: '适合朋友球局和圈层活动，活跃自然，边界清楚。'
  },
  {
    id: 'ast_golf_06',
    assistantNo: 'BA-1536',
    workName: '秦若川',
    city: '广州',
    avatarUrl: '/assets/assistants/golf-06.jpg',
    styleTags: ['大方', '稳', '礼仪感'],
    sceneSkills: ['高尔夫商务同场', '客户接待', '商务宴请'],
    businessSkills: ['球局接待', '餐叙衔接', '称呼核对'],
    talents: ['高尔夫下场 40+ 次', '粤语普通话双语切换', '商务礼仪培训 100 小时'],
    intro: '适合球局转晚宴。前后场能接上，不断档。',
    complianceNote,
    recommendReason: '适合球局后餐叙衔接，强项是礼仪、称呼和转场安排。'
  },
  {
    id: 'ast_city_01',
    assistantNo: 'BA-1602',
    workName: '沈南枝',
    city: '上海',
    avatarUrl: '/assets/assistants/city-01.jpg',
    styleTags: ['可靠', '本地通', '细节控'],
    sceneSkills: ['城市临时管家', '客户接待', '商务宴请'],
    businessSkills: ['到访动线', '临时事项统筹', '贵宾照应'],
    talents: ['上海接待动线 120+ 条', '英语接待 80+ 场', '摄影修图 500+ 张'],
    intro: '适合外地贵宾到访。路线、时间、称呼，都能提前稳住。',
    complianceNote,
    recommendReason: '适合临时到访和多点行程，强项是动线清晰、反应快。'
  },
  {
    id: 'ast_city_02',
    assistantNo: 'BA-1668',
    workName: '白以宁',
    city: '北京',
    avatarUrl: '/assets/assistants/city-02.jpg',
    styleTags: ['端正', '礼宾', '稳重'],
    sceneSkills: ['城市临时管家', '客户接待', '私人茶会'],
    businessSkills: ['政商务礼仪', '长辈接待', '场地建议'],
    talents: ['北京文化线路 60+ 条', '书法临帖 4 年', '普通话一级乙等'],
    intro: '适合规格高的接待。礼貌端正，安排有章法。',
    complianceNote,
    recommendReason: '适合北京重要客户接待和长辈场景，稳重、守边界、少废话。'
  },
  {
    id: 'ast_city_03',
    assistantNo: 'BA-1721',
    workName: '谢云舒',
    city: '深圳',
    avatarUrl: '/assets/assistants/city-03.jpg',
    styleTags: ['高效', '国际化', '反应快'],
    sceneSkills: ['城市临时管家', '项目沟通', '高端酒会'],
    businessSkills: ['中英切换', '临时改程', '商务沙龙衔接'],
    talents: ['英语商务沟通 100+ 场', '网球 NTRP 3.0', '展会接待 50+ 场'],
    intro: '适合节奏快的客户。改程不慌，信息不乱。',
    complianceNote,
    recommendReason: '适合深圳快节奏商务到访，能处理临时变化和多方协调。'
  },
  {
    id: 'ast_city_04',
    assistantNo: 'BA-1790',
    workName: '罗知予',
    city: '杭州',
    avatarUrl: '/assets/assistants/city-04.jpg',
    styleTags: ['审美好', '温和', '城市感'],
    sceneSkills: ['城市临时管家', '私人茶会', '客户接待'],
    businessSkills: ['城市审美路线', '茶会衔接', '低干扰礼宾'],
    talents: ['杭州审美路线 45 条', '茶席布置 60+ 次', '美术馆观展 100+ 次'],
    intro: '适合看重体验的客户。路线不俗，安排不浮夸。',
    complianceNote,
    recommendReason: '适合杭州城市体验和茶叙衔接，审美在线，节奏舒服。'
  },
  {
    id: 'ast_city_05',
    assistantNo: 'BA-1833',
    workName: '段清和',
    city: '成都',
    avatarUrl: '/assets/assistants/city-05.jpg',
    styleTags: ['松弛', '会安排', '亲和'],
    sceneSkills: ['城市临时管家', '轻商务接待', '高端酒会'],
    businessSkills: ['本地资源建议', '朋友局衔接', '情绪照应'],
    talents: ['成都本地路线 80+ 条', '民谣吉他曲目 30 首', '徒步 180+ 公里'],
    intro: '适合临时来访。安排舒服，不端着，也不乱热情。',
    complianceNote,
    recommendReason: '适合成都休闲商务到访，能把松弛感和分寸感同时做好。'
  },
  {
    id: 'ast_city_06',
    assistantNo: 'BA-1905',
    workName: '梅若安',
    city: '广州',
    avatarUrl: '/assets/assistants/city-06.jpg',
    styleTags: ['干练', '周到', '南方礼宾'],
    sceneSkills: ['城市临时管家', '客户接待', '商务宴请'],
    businessSkills: ['粤语接待', '晚宴衔接', '临时事项处理'],
    talents: ['粤语普通话双语切换', '广州动线 90+ 条', '急救培训 24 小时'],
    intro: '适合高要求临时接待。响应快，事落地，人不乱。',
    complianceNote,
    recommendReason: '适合广州多点接待和饭局衔接，优势是快、稳、细。'
  }
];

export const mockOrders: BookingOrder[] = [
  {
    id: 'ord_001',
    orderNo: 'BS20260525001',
    status: 'pending_payment',
    sceneName: '商务宴请',
    city: '上海',
    serviceTime: '2026-06-02 19:00',
    assistantCount: 1,
    depositAmount: 600,
    serviceFee: 1800,
    paidAmount: 0,
    createdAt: '2026-05-25 10:30',
    boundaryConfirmed: false
  },
  {
    id: 'ord_002',
    orderNo: 'BS20260521002',
    status: 'brief_preparing',
    sceneName: '客户接待',
    city: '北京',
    serviceTime: '2026-05-29 18:30',
    assistantCount: 2,
    depositAmount: 1200,
    serviceFee: 3600,
    paidAmount: 1200,
    createdAt: '2026-05-21 16:20',
    boundaryConfirmed: true
  },
  {
    id: 'ord_003',
    orderNo: 'BS20260518003',
    status: 'completed',
    sceneName: '商务宴请',
    city: '上海',
    serviceTime: '2026-05-20 19:00',
    assistantCount: 2,
    depositAmount: 1200,
    serviceFee: 3600,
    paidAmount: 1200,
    createdAt: '2026-05-18 14:12',
    boundaryConfirmed: true,
    reviewStatus: 'pending',
    reviewToken: 'review_BS20260518003',
    assistants: [
      {
        assistantId: 'ast_001',
        assistantNo: 'BA-0218',
        workName: '林澈',
        city: '上海',
        avatarUrl: assistants[0].avatarUrl,
        styleTags: assistants[0].styleTags,
        sceneSkills: assistants[0].sceneSkills
      },
      {
        assistantId: 'ast_003',
        assistantNo: 'BA-0521',
        workName: '周予安',
        city: '深圳',
        avatarUrl: assistants[2].avatarUrl,
        styleTags: assistants[2].styleTags,
        sceneSkills: assistants[2].sceneSkills
      }
    ]
  }
];

export const staffMealBriefs: StaffMealBrief[] = [
  {
    id: 'brief_001',
    orderId: '11111111-1111-1111-1111-111111111111',
    orderNo: 'BS20260521002',
    status: 'approved',
    banquetTheme: '外地客户到访接待晚宴',
    sceneName: '客户接待',
    city: '北京',
    serviceTime: '2026-05-29 18:30',
    attendeeCount: 7,
    dressCode: '深色商务装，低饱和配饰，整体干净利落。',
    assistantVisibleBrief: '本场为外地客户接待晚宴。目标是让初次会面更自然，建议围绕城市印象、行业趋势、项目经验等轻商务话题展开。注意保持克制，不主动触碰价格底线、竞品负面评价和客户个人隐私。',
    recommendedTopics: ['北京城市印象', '行业趋势', '客户过往项目经验', '团队协作方式'],
    tabooTopics: ['具体价格底线', '竞品负面评价', '客户个人隐私'],
    roleAssignments: [
      { role: '开场协同', owner: 'BA-0346 许知意', responsibility: '提前到场确认座位与称呼，开局协助自然寒暄。' },
      { role: '话题承接', owner: 'BA-0521 周予安', responsibility: '围绕城市到访、行业趋势承接轻商务话题。' }
    ],
    attentionPoints: ['客户到场后先由主陪介绍，助理不主动切入核心议题', '如出现敏感问题，及时转向项目经验或城市话题', '全程不交换私人联系方式'],
    tasks: [
      { id: 'task_001', title: '服务前阅读餐前简报', detail: '确认宴请主题、现场氛围需求和禁忌话题。', role: '服务团队', status: 'pending', sortOrder: 10 },
      { id: 'task_002', title: '确认着装与到场时间', detail: '按深色商务装执行，服务前 20 分钟到场。', role: '服务团队', status: 'pending', sortOrder: 20 },
      { id: 'task_003', title: '准备推荐话题', detail: '北京城市印象、行业趋势、客户过往项目经验。', role: '服务团队', status: 'pending', sortOrder: 30 },
      { id: 'task_004', title: '避开禁忌话题', detail: '具体价格底线、竞品负面评价、客户个人隐私。', role: '服务团队', status: 'pending', sortOrder: 40 }
    ]
  }
];
